-- Testbed GEB/GTP schema — matches testbed seeder column names.
-- No FK constraints (local dev user may lack REFERENCES privilege).

USE testbed;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS GTP_USER_GROUP_ROLE;
DROP TABLE IF EXISTS GTP_USER_ENTITY;
DROP TABLE IF EXISTS GTP_ENTITY_ROLE;
DROP TABLE IF EXISTS GTP_COMPANY_ROLE;
DROP TABLE IF EXISTS GTP_ROLE_PERMISSION;
DROP TABLE IF EXISTS GTP_GROUP_ROLE;
DROP TABLE IF EXISTS GTP_USER;
DROP TABLE IF EXISTS GTP_GROUP;
DROP TABLE IF EXISTS GTP_ENTITY;
DROP TABLE IF EXISTS GTP_ROLE;
DROP TABLE IF EXISTS GTP_PERMISSION;

CREATE TABLE GTP_PERMISSION (
    PERMISSION_ID INT NOT NULL AUTO_INCREMENT,
    PERMISSION VARCHAR(255) NOT NULL,
    PRIMARY KEY (PERMISSION_ID),
    UNIQUE KEY UK_GTP_PERMISSION (PERMISSION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_ROLE (
    ROLE_ID INT NOT NULL AUTO_INCREMENT,
    ROLENAME VARCHAR(255) NOT NULL,
    ROLETYPE VARCHAR(64) DEFAULT 'FUNCTIONAL',
    ROLEASSIGNER VARCHAR(255) DEFAULT '',
    ROLEDEST VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ROLE_ID),
    UNIQUE KEY UK_GTP_ROLENAME (ROLENAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_GROUP (
    GROUP_ID INT NOT NULL AUTO_INCREMENT,
    GROUPNAME VARCHAR(255) NOT NULL,
    COMPANY_ID INT DEFAULT NULL,
    PRIMARY KEY (GROUP_ID),
    UNIQUE KEY UK_GTP_GROUPNAME (GROUPNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_ENTITY (
    ENTITY_ID INT NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    ABBV_NAME VARCHAR(64) NOT NULL,
    COMPANY_ID INT NOT NULL,
    COUNTRY VARCHAR(8) DEFAULT 'SG',
    CONTACT_EMAIL VARCHAR(255) DEFAULT '',
    CONTACT_PERSON VARCHAR(255) DEFAULT '',
    BRCH_CODE VARCHAR(32) DEFAULT '',
    SUBSCRIPTION_CODE VARCHAR(32) DEFAULT '',
    DOM VARCHAR(64) DEFAULT 'CORPORATE',
    PRIMARY KEY (ENTITY_ID),
    UNIQUE KEY UK_GTP_ENTITY_ABBV (ABBV_NAME),
    KEY IDX_GTP_ENTITY_COMPANY (COMPANY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_USER (
    USER_ID INT NOT NULL AUTO_INCREMENT,
    LOGIN_ID VARCHAR(255) NOT NULL,
    PASSWORD_VALUE VARCHAR(255) NOT NULL,
    FIRST_NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255),
    COMPANY_ID INT DEFAULT NULL,
    COMPANY_ABBV_NAME VARCHAR(64) DEFAULT '',
    ACTV_FLAG CHAR(1) DEFAULT 'Y',
    COUNTRY VARCHAR(8) DEFAULT 'SG',
    DOM VARCHAR(64) DEFAULT 'CORPORATE',
    PHONE VARCHAR(64) DEFAULT '',
    FAX VARCHAR(64) DEFAULT '',
    TIME_ZONE VARCHAR(64) DEFAULT 'Asia/Singapore',
    LANGUAGE VARCHAR(16) DEFAULT 'en',
    REFERENCE VARCHAR(255) DEFAULT '',
    CREATED DATETIME DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (USER_ID),
    UNIQUE KEY UK_GTP_LOGIN_ID (LOGIN_ID),
    KEY IDX_GTP_USER_COMPANY (COMPANY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_ROLE_PERMISSION (
    ROLE_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL,
    PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    KEY IDX_GTP_RP_ROLE (ROLE_ID),
    KEY IDX_GTP_RP_PERM (PERMISSION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_GROUP_ROLE (
    GROUP_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (GROUP_ID, ROLE_ID),
    KEY IDX_GTP_GR_GROUP (GROUP_ID),
    KEY IDX_GTP_GR_ROLE (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_USER_GROUP_ROLE (
    USER_ID INT NOT NULL,
    GROUP_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    PRIMARY KEY (USER_ID, GROUP_ID, ROLE_ID),
    KEY IDX_GTP_UGR_USER (USER_ID),
    KEY IDX_GTP_UGR_GROUP (GROUP_ID),
    KEY IDX_GTP_UGR_ROLE (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_USER_ENTITY (
    USER_ID INT NOT NULL,
    ENTITY_ID INT NOT NULL,
    DEFAULT_ENTITY CHAR(1) DEFAULT 'N',
    ABBV_NAME VARCHAR(64) DEFAULT '',
    USER_ABBV_NAME VARCHAR(255) DEFAULT '',
    PRIMARY KEY (USER_ID, ENTITY_ID),
    KEY IDX_GTP_UE_USER (USER_ID),
    KEY IDX_GTP_UE_ENTITY (ENTITY_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_COMPANY_ROLE (
    COMPANY_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    ROLE_DESCRIPTION VARCHAR(255) DEFAULT '',
    PRIMARY KEY (COMPANY_ID, ROLE_ID),
    KEY IDX_GTP_CR_ROLE (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE GTP_ENTITY_ROLE (
    ENTITY_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,
    ROLE_DESCRIPTION VARCHAR(255) DEFAULT '',
    PRIMARY KEY (ENTITY_ID, ROLE_ID),
    KEY IDX_GTP_ER_ENTITY (ENTITY_ID),
    KEY IDX_GTP_ER_ROLE (ROLE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
