[DEFAULT]
# Specify the absolute or relative path where projects will be created
root_dir = C:/MyGeneratedProjects

[SPRING4]
project_name = spring4-legacy-mysql
package_name = com.example.legacy
db_type = mysql

[SPRING6]
project_name = spring6-jakarta-oracle
package_name = com.example.modern
db_type = oracle