import os
import sys

TEMPLATE = {
    'app.js': '''
const express = require('express');
const path = require('path');
const config = require('./Config/config');
const router = require('./router/routes');

const app = express();
app.set('views', path.join(__dirname, 'view'));
app.set('view engine', 'ejs');
app.use(express.json());
app.use(express.urlencoded({ extended: false }));
app.use('/', router);

const PORT = config.port;
app.listen(PORT, () => {
  console.log(`Server running on http://localhost:${PORT}`);
});
''',
    'Config/config.js': '''
module.exports = {
  appName: 'My Node Express App',
  port: process.env.PORT || 3000
};
''',
    'router/routes.js': '''
const express = require('express');
const router = express.Router();

router.get('/', (req, res) => {
  res.render('index', { title: 'Express Modular App', message: 'Welcome to your modular Express app!' });
});

module.exports = router;
''',
    'view/index.ejs': '''
<!DOCTYPE html>
<html>
<head>
  <title><%= title %></title>
</head>
<body>
  <h1><%= message %></h1>
</body>
</html>
''',
    'README.md': '# Node + Express Template\n\nGenerated by Python script.'
}

def create_project(project_name):
    os.makedirs(project_name, exist_ok=True)
    for path, content in TEMPLATE.items():
        file_path = os.path.join(project_name, path)
        os.makedirs(os.path.dirname(file_path), exist_ok=True)
        with open(file_path, 'w') as f:
            f.write(content)
    print(f"Node+Express template created in: {project_name}")

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python nodeProjectCreate.py <project_name>")
        sys.exit(1)
    project_name = sys.argv[1]
    create_project(project_name)
